### ISSUE TITLE
Restrict the expense button if amount is more than balance

### ISSUE THREAD

**Issue by srinidhifd** [shruti-sen2004/BudgetBuddy#16]
If we have only 9000 in account balance , how we can have expense of 90000 .
It is showing -81000 which is not possible in reality.
So I would like to add validation logic for this . Expense button logic will work only when amount is less than or equal to Balance.

Screenshots:

![image](https://github.com/user-attachments/assets/164e5351-5ee3-43b4-bf6f-802fb55b1b74)
![image](https://github.com/user-attachments/assets/ac372b5d-cd1c-467b-91b4-2fc1393fbd29)

@shruti-sen2004 Please assign me this issue under Hactoberfest label . I would like to work on this .

**Comment by ishan657** [comment]
HI @srinidhifd 
I would love to work on this issue, kindly assign it to me 
thankyou

**Comment by shruti-sen2004** [comment]
Hi @srinidhifd ,
Thank you for your suggestion but I wanted that feature to work this way because if the total goes into negative, it indicates that they’ve spent more than they’ve earned for that particular month or period. It’s meant to show overspending within a timeframe, not necessarily what the person has in total. 
Best regards,
Shruti

**Comment by srinidhifd** [comment]
@shruti-sen2004 Yes even that seems one of the ways to handle overspending.
